    # Generated by Django 2.1.4 on 2019-06-23 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='2 literowy kod kraju', max_length=2)),
                ('name', models.CharField(help_text='Nazwa kraju', max_length=32)),
            ],
            options={
                'verbose_name': 'Kraj',
                'verbose_name_plural': 'Kraje',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Powiat', max_length=32)),
            ],
            options={
                'verbose_name': 'Powiat',
                'verbose_name_plural': 'Region - Powiaty',
            },
        ),
        migrations.CreateModel(
            name='CourtBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nazwa księgi', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CourtBookSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_type', models.IntegerField(choices=[(1, 'Oryginał'), (2, 'Kopia'), (3, 'Odpis'), (4, 'Sumariusz')], default=1)),
                ('note', models.TextField(blank=True, help_text='Notatka')),
                ('date_created', models.DateTimeField(blank=True, help_text='Data utworzenia', null=True)),
                ('date_modified', models.DateTimeField(blank=True, help_text='Data utworzenia', null=True)),
                ('zespol', models.CharField(blank=True, max_length=64)),
                ('sygnatura', models.CharField(blank=True, max_length=64)),
                ('date_from', models.IntegerField(default=1800, help_text='Zakres dat: od roku')),
                ('date_to', models.IntegerField(default=1900, help_text='Zakres dat: do roku')),
                ('book', models.ForeignKey(help_text='Księga', on_delete=django.db.models.deletion.DO_NOTHING, to='core.CourtBook')),
            ],
            options={
                'verbose_name': 'Zbiór danych',
                'verbose_name_plural': 'Zbiory danych',
            },
        ),
        migrations.CreateModel(
            name='CourtOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa kancelarii', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dekanat', max_length=64)),
                ('url', models.URLField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Dekanat',
                'verbose_name_plural': 'Region - Dekanaty',
            },
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Diecezja', max_length=64)),
                ('short', models.CharField(blank=True, max_length=3)),
                ('url', models.URLField(blank=True, max_length=128, null=True)),
                ('public', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
            ],
            options={
                'verbose_name': 'Diecezja',
                'verbose_name_plural': 'Region - Diecezje',
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parafia pod wezwaniem', max_length=32)),
                ('religion', models.IntegerField(choices=[(3, 'Wschodni Kościół Staroobrzędowy'), (1, 'Kościół rzymskokatolicki'), (5, 'Kościół Ewangelicko-Augsburski'), (2, 'Żydowski Związek Wyznaniowy'), (6, 'Polski Kościół Prawosławny'), (4, 'Muzułmański Związek Religijny')], default=1)),
                ('year', models.IntegerField(blank=True, help_text='Data erygowania')),
                ('access', models.IntegerField(choices=[(0, 'Otwarty'), (1, 'Zamknięty')], default=0)),
                ('place', models.CharField(help_text='Miejscowość', max_length=32)),
                ('postal_code', models.CharField(help_text='Kod pocztowy', max_length=16)),
                ('postal_place', models.CharField(help_text='Poczta', max_length=32)),
                ('address', models.CharField(help_text='Adres, ulica i numer', max_length=32)),
                ('geo_lat', models.FloatField(blank=True)),
                ('geo_lng', models.FloatField(blank=True)),
                ('geo_validated', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, help_text=16, max_length=32)),
                ('link', models.URLField(blank=True)),
                ('gen_id', models.IntegerField(default=0, unique=True)),
                ('szwa_id', models.CharField(blank=True, max_length=64)),
                ('fs_catalog_id', models.CharField(blank=True, max_length=64)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
                ('county', models.ForeignKey(help_text='Powiat', on_delete=django.db.models.deletion.DO_NOTHING, to='core.County')),
                ('deanery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Deanery')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Diocese')),
            ],
            options={
                'verbose_name': 'Parafia',
                'verbose_name_plural': 'Parafie',
            },
        ),
        migrations.CreateModel(
            name='ParishComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, help_text='Tresc komentarza')),
                ('date_created', models.DateTimeField(blank=True, help_text='Data utworzenia', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Widocznosc komentarza')),
                ('parish', models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
                ('user', models.ForeignKey(help_text='Autor komentarza', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParishPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('geo_lat', models.FloatField(blank=True)),
                ('geo_lng', models.FloatField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_type', models.IntegerField(choices=[(1, 'Oryginał'), (2, 'Kopia'), (3, 'Odpis'), (4, 'Sumariusz')], default=1)),
                ('note', models.TextField(blank=True, help_text='Notatka')),
                ('date_created', models.DateTimeField(blank=True, help_text='Data utworzenia', null=True)),
                ('date_modified', models.DateTimeField(blank=True, help_text='Data utworzenia', null=True)),
                ('type_b', models.BooleanField(default=False, help_text='Akty urodzenia')),
                ('type_d', models.BooleanField(default=False, help_text='Akty zgonu')),
                ('type_m', models.BooleanField(default=False, help_text='Akty małżeństwa')),
                ('type_a', models.BooleanField(default=False, help_text='Alegaty')),
                ('type_sum_only', models.BooleanField(default=False, help_text='Dostępny tylko sumariusz')),
                ('date_from', models.IntegerField(default=1800, help_text='Zakres dat: od roku')),
                ('date_to', models.IntegerField(default=1900, help_text='Zakres dat: do roku')),
                ('parish', models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
            options={
                'verbose_name': 'Zbiór danych',
                'verbose_name_plural': 'Zbiory danych',
            },
        ),
        migrations.CreateModel(
            name='ParishSourceExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nazwa grupy dokumentów', max_length=32)),
                ('url', models.URLField(blank=True, help_text='Adres url pod którym dokumenty są dostępne')),
                ('parish', models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa województwa', max_length=32)),
                ('short', models.CharField(blank=True, max_length=2)),
                ('public', models.BooleanField(default=False)),
                ('country', models.ForeignKey(help_text='Kraj', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
            ],
            options={
                'verbose_name': 'Województwo',
                'verbose_name_plural': 'Region - Województwa',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short', models.CharField(blank=True, max_length=16)),
                ('url', models.URLField(blank=True, max_length=64)),
                ('group', models.CharField(blank=True, choices=[('AP', 'Archiwum Państwowe'), ('AD', 'Archiwym Diecezjalne'), ('Other', 'Inne')], default='Other', help_text='Grupa źródeł', max_length=32)),
            ],
            options={
                'verbose_name': 'Zbiór danych - źródło',
                'verbose_name_plural': 'Zbiory danych - źródła',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, help_text='Imię', max_length=64)),
                ('lastname', models.CharField(blank=True, help_text='Nazwisko', max_length=64)),
                ('full_access', models.BooleanField(default=False, help_text='Pełen dostęp do danych')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZiemiaIRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa ziemi', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'ziemie I RP',
            },
        ),
        migrations.AddField(
            model_name='parishsource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Source'),
        ),
        migrations.AddField(
            model_name='parishsource',
            name='user',
            field=models.ForeignKey(help_text='Autor rekordu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parish',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Province'),
        ),
        migrations.AddField(
            model_name='parish',
            name='ziemia_i_rp',
            field=models.ForeignKey(help_text='Ziemia I RP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ZiemiaIRP'),
        ),
        migrations.AddField(
            model_name='deanery',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Diocese'),
        ),
        migrations.AddField(
            model_name='courtoffice',
            name='ziemia_i_rp',
            field=models.ForeignKey(help_text='Ziemia I RP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ZiemiaIRP'),
        ),
        migrations.AddField(
            model_name='courtbooksource',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Source'),
        ),
        migrations.AddField(
            model_name='courtbooksource',
            name='user',
            field=models.ForeignKey(help_text='Autor rekordu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courtbook',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.CourtOffice'),
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(help_text='Województwo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Province'),
        ),
    ]
