# Generated by Django 2.1.4 on 2018-12-22 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='2 literowy kod kraju', max_length=2)),
                ('name', models.CharField(help_text='Nazwa kraju', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Powiat', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dekanat', max_length=64)),
                ('url', models.URLField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Diecezja', max_length=64)),
                ('url', models.URLField(blank=True, max_length=128)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(blank=True)),
                ('type', models.IntegerField(choices=[(0, 'Documents'), (1, 'Photos'), (2, 'Indexes')])),
                ('type_b', models.BooleanField(default=False, help_text='Akty urodzenia')),
                ('type_d', models.BooleanField(default=False, help_text='Akty zgonu')),
                ('type_m', models.BooleanField(default=False, help_text='Akty małżeństwa')),
                ('type_a', models.BooleanField(default=False, help_text='Alegaty')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('date_excepts', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Parafia pod wezwaniem', max_length=32)),
                ('religion', models.IntegerField(choices=[(1, 'Kościół rzymskokatolicki')], default=1)),
                ('year', models.IntegerField(blank=True, help_text='Data erygowania')),
                ('access', models.IntegerField(choices=[(0, 'Otwarty'), (1, 'Zamknięty')], default=0)),
                ('place', models.CharField(help_text='Miejscowość', max_length=32)),
                ('postal_code', models.CharField(help_text='Kod pocztowy', max_length=16)),
                ('postal_place', models.CharField(help_text='Poczta', max_length=32)),
                ('address', models.CharField(help_text='Adres, ulica i numer', max_length=32)),
                ('geo_lat', models.FloatField(blank=True)),
                ('geo_lon', models.FloatField(blank=True)),
                ('phone', models.CharField(help_text=16, max_length=32)),
                ('link', models.URLField(blank=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
                ('county', models.ForeignKey(help_text='Powiat', on_delete=django.db.models.deletion.DO_NOTHING, to='core.County')),
                ('deanery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Deanery')),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Diocese')),
            ],
        ),
        migrations.CreateModel(
            name='ParishPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('geo_lat', models.FloatField(blank=True)),
                ('geo_lon', models.FloatField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_key', models.CharField(max_length=16)),
                ('data', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True)),
                ('documents_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.DocumentGroup')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa województwa', max_length=32)),
                ('country', models.ForeignKey(help_text='Kraj', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country')),
            ],
        ),
        migrations.AddField(
            model_name='parish',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Province'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='parish_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ParishRef'),
        ),
        migrations.AddField(
            model_name='deanery',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Diocese'),
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(help_text='Województwo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Province'),
        ),
    ]
