# Generated by Django 2.0 on 2017-12-20 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Photos'), (2, 'Indexes')])),
                ('type_b', models.BooleanField()),
                ('type_d', models.BooleanField()),
                ('type_m', models.BooleanField()),
                ('type_a', models.BooleanField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=32)),
                ('geo_lat', models.FloatField(blank=True)),
                ('geo_lon', models.FloatField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ParishRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
        migrations.CreateModel(
            name='ParishUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='parishref',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Source'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish'),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='parish_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ParishRef'),
        ),
    ]
