# Generated by Django 2.2.2 on 2019-07-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtbook',
            options={'verbose_name': 'Księga sądowa', 'verbose_name_plural': 'Księgi sądowe'},
        ),
        migrations.AlterModelOptions(
            name='courtbooksource',
            options={'verbose_name': 'Księga sądowa - zbiór danych', 'verbose_name_plural': 'Księgi sądowe - zbiory danych'},
        ),
        migrations.AlterModelOptions(
            name='courtoffice',
            options={'verbose_name': 'Kancelaria', 'verbose_name_plural': 'Kancelarie'},
        ),
        migrations.AlterModelOptions(
            name='parishsource',
            options={'verbose_name': 'Parafia - Zbiór danych', 'verbose_name_plural': 'Parafie - zbiory danych'},
        ),
        migrations.AddField(
            model_name='parishuser',
            name='favorite',
            field=models.BooleanField(default=False, help_text='Czy parafia nalezy do ulubionych usera'),
        ),
        migrations.AddField(
            model_name='parishuser',
            name='manager',
            field=models.BooleanField(default=False, help_text='Czy mamy uprawnienia do zarządzania parafią'),
        ),
        migrations.AlterField(
            model_name='courtoffice',
            name='ziemia_i_rp',
            field=models.ForeignKey(blank=True, help_text='Ziemia I RP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ZiemiaIRP'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='deanery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Deanery'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='religion',
            field=models.IntegerField(choices=[(1, 'Kościół rzymskokatolicki'), (2, 'Żydowski Związek Wyznaniowy'), (3, 'Wschodni Kościół Staroobrzędowy'), (4, 'Muzułmański Związek Religijny'), (5, 'Kościół Ewangelicko-Augsburski'), (6, 'Polski Kościół Prawosławny')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='parishuser',
            unique_together={('parish', 'user')},
        ),
    ]
