# Generated by Django 2.2.2 on 2019-07-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190708_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishuser',
            name='manager_request',
            field=models.BooleanField(default=False, help_text='Zadanie dostepu do zarzadzania parafia'),
        ),
        migrations.AddField(
            model_name='parishuser',
            name='manager_request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
