# Generated by Django 2.1.4 on 2018-12-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='deanery',
            options={'verbose_name_plural': 'deaneries'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name_plural': 'parishes'},
        ),
        migrations.AddField(
            model_name='province',
            name='short',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='parish',
            name='phone',
            field=models.CharField(blank=True, help_text=16, max_length=32),
        ),
    ]
