# Generated by Django 2.1.4 on 2018-12-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diocese_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diocese',
            name='url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
