# Generated by Django 2.1.4 on 2018-12-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181223_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='gen_id',
            field=models.IntegerField(default=0),
        ),
    ]
