# Generated by Django 2.2.3 on 2019-07-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190720_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Parish'),
        ),
        migrations.AlterField(
            model_name='source',
            name='group',
            field=models.CharField(blank=True, choices=[('AP', 'Archiwum Państwowe - PL'), ('AD', 'Archiwum Diecezjalne - PL'), ('PAR', 'Archiwum Parafialne'), ('Other', 'Inne')], default='Other', help_text='Grupa źródeł', max_length=32),
        ),
    ]
