# Generated by Django 2.1.4 on 2018-12-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181223_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parish',
            old_name='geo_lon',
            new_name='geo_lng',
        ),
    ]
