# Generated by Django 2.2.2 on 2019-08-04 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190728_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtbook',
            name='type',
            field=models.CharField(blank=True, choices=[('grodzkie', 'Grodzkie'), ('ziemskie', 'Ziemskie'), ('podkomorskie', 'Podkomorskie'), ('biskupie', 'Biskupie'), ('bartne', 'Bartne'), ('wojtowskie', 'Wójtowskie'), ('radzieckie', 'Radzieckie'), ('lawnicze', 'Ławnicze'), ('kapicjana', 'Kapicjana'), ('inne', 'Inne')], max_length=32),
        ),
        migrations.AddField(
            model_name='courtoffice',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Country'),
        ),
        migrations.AddField(
            model_name='parish',
            name='place2',
            field=models.CharField(blank=True, help_text='Miejscowość, nazwa historyczna', max_length=32),
        ),
        migrations.AddField(
            model_name='parishsource',
            name='type_zap',
            field=models.BooleanField(default=False, help_text='Zapowiedzi'),
        ),
    ]
