# Generated by Django 2.1.4 on 2019-01-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181223_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgroup',
            name='date_excepts',
            field=models.TextField(blank=True, help_text='Lata pominięte'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='date_from',
            field=models.IntegerField(default=1800, help_text='Zakres dat: od roku'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='date_to',
            field=models.IntegerField(default=1900, help_text='Zakres dat: do roku'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='name',
            field=models.CharField(help_text='Nazwa grupy dokumentów', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='note',
            field=models.TextField(blank=True, help_text='Notatka'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='parish',
            field=models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='type',
            field=models.IntegerField(choices=[(0, 'Documents'), (1, 'Photos'), (2, 'Indexes')], help_text='Typ dokumentów'),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='url',
            field=models.URLField(blank=True, help_text='Adres url pod którym dokumenty są dostępne'),
        ),
    ]
