# Generated by Django 2.2.2 on 2019-08-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190804_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='parish',
        ),
        migrations.AddField(
            model_name='parishsource',
            name='source_parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_parish', to='core.Parish'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='ziemia_i_rp',
            field=models.ForeignKey(blank=True, help_text='Ziemia I RP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ZiemiaIRP'),
        ),
        migrations.AlterField(
            model_name='parishsource',
            name='parish',
            field=models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, related_name='parish', to='core.Parish'),
        ),
    ]
