# Generated by Django 2.1.4 on 2019-01-07 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190106_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parishplace',
            old_name='geo_lon',
            new_name='geo_lng',
        ),
        migrations.RemoveField(
            model_name='documentgroup',
            name='parish_ref',
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.DocumentSource'),
            preserve_default=False,
        ),
    ]
