# Generated by Django 2.1.4 on 2019-01-09 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20190107_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgroup',
            name='date_created',
            field=models.DateTimeField(blank=True, help_text='Data utworzenia', null=True),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='date_modified',
            field=models.DateTimeField(blank=True, help_text='Data utworzenia', null=True),
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='user',
            field=models.ForeignKey(help_text='Autor rekordu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
