# Generated by Django 2.1.4 on 2019-01-13 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20190109_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, help_text='Tresc komentarza')),
                ('date_created', models.DateTimeField(blank=True, help_text='Data utworzenia', null=True)),
                ('visible', models.BooleanField(default=True, help_text='Widocznosc komentarza')),
                ('parish', models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
                ('user', models.ForeignKey(help_text='Autor komentarza', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
