# Generated by Django 2.2.2 on 2019-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191016_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, help_text='Opis na stronę główną'),
        ),
    ]
