# Generated by Django 2.1.4 on 2019-01-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_parishcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiemiaIRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa ziemi', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'ziemie I RP',
            },
        ),
        migrations.AddField(
            model_name='parish',
            name='ziemia_i_rp',
            field=models.ForeignKey(help_text='Ziemia I RP', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ZiemiaIRP'),
        ),
    ]
