# Generated by Django 2.2.2 on 2019-12-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_country_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='date_updated',
            field=models.DateTimeField(default=None, help_text='Data aktualizacji', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='historical_period',
            field=models.IntegerField(choices=[(1, 'I RP'), (2, 'II RP'), (3, 'III RP'), (4, 'RZ')], default=1, help_text='Okres historyczny'),
        ),
        migrations.AlterField(
            model_name='courtbooksource',
            name='copy_type',
            field=models.IntegerField(choices=[(None, ''), (6, 'Ksiega'), (4, 'Sumariusz'), (7, 'Reptularz'), (99, '-------------------'), (1, 'Oryginał'), (2, 'Duplikat ASC / USC'), (3, 'Odpis'), (5, 'Kopia dekanalna')], default=None),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county',
            field=models.ForeignKey(help_text='Powiat (R3)', limit_choices_to=models.Q(province__country__historical_period=3), on_delete=django.db.models.deletion.DO_NOTHING, to='core.County'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county_r1',
            field=models.ForeignKey(blank=True, help_text='Powiat (R1)', limit_choices_to=models.Q(province__country__historical_period=1), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_r1', to='core.County'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county_r2',
            field=models.ForeignKey(blank=True, help_text='Powiat (R2)', limit_choices_to=models.Q(province__country__historical_period=2), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_r2', to='core.County'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county_rz',
            field=models.ForeignKey(blank=True, help_text='Powiat (RZ)', limit_choices_to=models.Q(province__country__historical_period=4), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_rz', to='core.County'),
        ),
        migrations.AlterField(
            model_name='parishsource',
            name='copy_type',
            field=models.IntegerField(choices=[(None, ''), (6, 'Ksiega'), (4, 'Sumariusz'), (7, 'Reptularz'), (99, '-------------------'), (1, 'Oryginał'), (2, 'Duplikat ASC / USC'), (3, 'Odpis'), (5, 'Kopia dekanalna')], default=None),
        ),
        migrations.AlterField(
            model_name='source',
            name='group',
            field=models.CharField(blank=True, choices=[('AP', 'Archiwa Państwowe (PL)'), ('AD', 'Archiwa Kościelne (PL)'), ('PAR', 'Archiwum Parafialne (ALL)'), ('BIB', 'Biblioteki'), ('USC', 'Urzędy Stanu Cywilnego'), ('AP_UA', 'Archiwa Państwowe (UA)'), ('AP_LT', 'Archiwa Państwowe (LT)'), ('AP_BY', 'Archiwa Państwowe (BY)'), ('AP_RU', 'Archiwa Państwowe (RU)'), ('AP_LV', 'Archiwa Państwowe (LV)'), ('AP_RO', 'Archiwa Państwowe (RO)'), ('A_Z', 'Archiwa Zagraniczne'), ('Other', 'Inne')], default='Other', help_text='Grupa źródeł', max_length=32),
        ),
    ]
