# Generated by Django 2.2.2 on 2020-01-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191224_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='century',
            field=models.CharField(blank=True, help_text='Wiek powstania', max_length=8),
        ),
    ]
