# Generated by Django 2.1.4 on 2019-01-30 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190126_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishrawdata',
            name='data_source',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='parishrawdata',
            name='parish_documentgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.DocumentGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='parishrawdata',
            unique_together={('data_source', 'data_key')},
        ),
    ]
