# Generated by Django 2.2.2 on 2020-01-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200125_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='address',
            field=models.CharField(blank=True, help_text='Adres, ulica i numer', max_length=32, null=True),
        ),
    ]
