# Generated by Django 2.1.4 on 2019-01-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20190130_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Kraj', 'verbose_name_plural': 'Kraje'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'Powiat', 'verbose_name_plural': 'Region - Powiaty'},
        ),
        migrations.AlterModelOptions(
            name='deanery',
            options={'verbose_name': 'Dekanat', 'verbose_name_plural': 'Region - Dekanaty'},
        ),
        migrations.AlterModelOptions(
            name='diocese',
            options={'verbose_name': 'Diecezja', 'verbose_name_plural': 'Region - Diecezje'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name': 'Parafia', 'verbose_name_plural': 'Parafie'},
        ),
        migrations.AlterModelOptions(
            name='parishrawdata',
            options={'verbose_name': 'Parafia - dane surowe', 'verbose_name_plural': 'Parafie - dane surowe'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Województwo', 'verbose_name_plural': 'Region - Województwa'},
        ),
        migrations.AlterField(
            model_name='parishrawdata',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish'),
        ),
    ]
