# Generated by Django 2.1.4 on 2019-01-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190130_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishrawdata',
            name='data_key',
            field=models.CharField(max_length=64),
        ),
    ]
