# Generated by Django 2.1.4 on 2019-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190130_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgroup',
            name='source_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='name',
            field=models.CharField(blank=True, help_text='Nazwa grupy dokumentów', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentgroup',
            name='type',
            field=models.IntegerField(choices=[(0, 'Akta metrykalne')], default=0, help_text='Typ dokumentów'),
        ),
    ]
