# Generated by Django 2.2.2 on 2020-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200308_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='address',
            field=models.CharField(blank=True, help_text='Adres, ulica i numer', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='parish',
            name='religion',
            field=models.IntegerField(choices=[(1, 'Kościół rzymskokatolicki'), (2, 'Żydowski Związek Wyznaniowy'), (3, 'Wschodni Kościół Staroobrzędowy'), (4, 'Muzułmański Związek Religijny'), (5, 'Kościół Ewangelicko-Augsburski'), (6, 'Polski Kościół Prawosławny'), (7, 'Kościół Greckokatolicki')], default=1),
        ),
    ]
