# Generated by Django 2.1.4 on 2019-04-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190416_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentgroup',
            options={'verbose_name': 'Zbiór danych', 'verbose_name_plural': 'Zbiory danych'},
        ),
        migrations.AlterModelOptions(
            name='documentsource',
            options={'verbose_name': 'Zbiór danych - źródło', 'verbose_name_plural': 'Zbiory danych - źródła'},
        ),
        migrations.AlterModelOptions(
            name='parishref',
            options={'verbose_name': 'Parafia - łacznik', 'verbose_name_plural': 'Parafie - połączenia'},
        ),
        migrations.AddField(
            model_name='parish',
            name='fs_catalog_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='parish',
            name='szwa_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
