# Generated by Django 2.2.2 on 2020-03-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200315_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='partial_done',
            field=models.BooleanField(default=False, help_text='Częściowo wypełniona, tj. są księgi jakieś wpisane.'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='all_done',
            field=models.BooleanField(default=False, help_text='Oznacza parafię całkowicie uzuepłnioną\xa0(wg wiedzy opiekunów). To pole nadpisuje pole częściowego wypełnienia.'),
        ),
    ]
