# Generated by Django 2.2.1 on 2019-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190420_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='geo_validated',
            field=models.BooleanField(default=False),
        ),
    ]
