# Generated by Django 2.2.2 on 2020-03-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_parish_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='a_par_for_auto_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='courtbooksource',
            name='copy_type',
            field=models.IntegerField(choices=[(0, ''), (6, 'Księga'), (4, 'Sumariusz'), (7, 'Reptularz')], default=0),
        ),
        migrations.AlterField(
            model_name='parishsource',
            name='copy_type',
            field=models.IntegerField(choices=[(0, ''), (6, 'Księga'), (4, 'Sumariusz'), (7, 'Reptularz')], default=0),
        ),
    ]
