# Generated by Django 2.2.18 on 2021-04-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200322_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='religion',
            field=models.IntegerField(choices=[(1, 'Kościół rzymskokatolicki'), (2, 'Żydowski Związek Wyznaniowy'), (3, 'Wschodni Kościół Staroobrzędowy'), (4, 'Muzułmański Związek Religijny'), (5, 'Kościół Ewangelicko-Augsburski'), (6, 'Polski Kościół Prawosławny'), (7, 'Kościół Greckokatolicki')], default=1),
        ),
        migrations.AddField(
            model_name='parish',
            name='deanery_r1',
            field=models.ForeignKey(blank=True, help_text='Dekanat (R1)', limit_choices_to=models.Q(diocese__country__historical_period=1), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deanery_r1', to='core.Deanery'),
        ),
        migrations.AddField(
            model_name='parish',
            name='deanery_r2',
            field=models.ForeignKey(blank=True, help_text='Dekanat (R2)', limit_choices_to=models.Q(diocese__country__historical_period=2), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deanery_r2', to='core.Deanery'),
        ),
        migrations.AddField(
            model_name='parish',
            name='deanery_rz',
            field=models.ForeignKey(blank=True, help_text='Dekanat (RZ)', limit_choices_to=models.Q(diocese__country__historical_period=4), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deanery_rz', to='core.Deanery'),
        ),
        migrations.AlterField(
            model_name='courtbooksource',
            name='copy_type',
            field=models.IntegerField(choices=[(0, ''), (6, 'Księga'), (4, 'Sumariusz'), (7, 'Reptularz')], default=6),
        ),
        migrations.AlterField(
            model_name='parishsource',
            name='copy_type',
            field=models.IntegerField(choices=[(0, ''), (6, 'Księga'), (4, 'Sumariusz'), (7, 'Reptularz')], default=6),
        ),
        migrations.CreateModel(
            name='ParishIndexSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(choices=[(1, 'Projekt Podlasie'), (0, 'Test')], default=0)),
                ('url', models.URLField(blank=True, help_text='Adres informacji o indexach')),
                ('checked_date', models.DateTimeField(blank=True, null=True)),
                ('parish', models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
    ]
