# Generated by Django 2.2.18 on 2021-04-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210401_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Kraj', 'verbose_name_plural': 'Region - Kraje'},
        ),
        migrations.AlterModelOptions(
            name='deanery',
            options={'ordering': ['name'], 'verbose_name': 'Dekanat', 'verbose_name_plural': 'Region - Dekanaty'},
        ),
        migrations.AlterModelOptions(
            name='diocese',
            options={'ordering': ['name'], 'verbose_name': 'Diecezja', 'verbose_name_plural': 'Region - Diecezje'},
        ),
        migrations.AddField(
            model_name='parishindexsource',
            name='raw_data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='historical_period',
            field=models.IntegerField(choices=[(1, 'I RP'), (2, 'II RP'), (3, 'III RP'), (4, 'RZ')], default=1, help_text='Kraje z dane okresu historycznego będą prezentowane wspólnie', verbose_name='Okres historyczny'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county_r1',
            field=models.ForeignKey(blank=True, help_text='Powiat w R1', limit_choices_to=models.Q(province__country__historical_period=1), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_r1', to='core.County'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county_r2',
            field=models.ForeignKey(blank=True, help_text='Powiat w R2', limit_choices_to=models.Q(province__country__historical_period=2), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_r2', to='core.County'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='county_rz',
            field=models.ForeignKey(blank=True, help_text='Powiat w RZ', limit_choices_to=models.Q(province__country__historical_period=4), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='county_rz', to='core.County'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='deanery',
            field=models.ForeignKey(blank=True, help_text='Dekanat', limit_choices_to=models.Q(diocese__country__historical_period=3), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Deanery'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='deanery_r1',
            field=models.ForeignKey(blank=True, help_text='Dekanat w R1', limit_choices_to=models.Q(diocese__country__historical_period=1), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deanery_r1', to='core.Deanery'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='deanery_r2',
            field=models.ForeignKey(blank=True, help_text='Dekanat w R2', limit_choices_to=models.Q(diocese__country__historical_period=2), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deanery_r2', to='core.Deanery'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='deanery_rz',
            field=models.ForeignKey(blank=True, help_text='Dekanat w RZ', limit_choices_to=models.Q(diocese__country__historical_period=4), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deanery_rz', to='core.Deanery'),
        ),
    ]
