# Generated by Django 2.2.18 on 2021-05-12 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210422_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='county',
            field=models.ForeignKey(help_text='Powiat (R3)', limit_choices_to=models.Q(province__country__historical_period=3), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.County'),
        ),
        migrations.AlterField(
            model_name='parishuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='source',
            name='group',
            field=models.CharField(blank=True, choices=[('AP', 'Archiwa Państwowe (PL)'), ('AD', 'Archiwa Kościelne (PL)'), ('PAR_LOC', 'Archiwum Parafialne - na miejscu'), ('PAR', 'Archiwum Parafialne - Inne'), ('A_Z', 'Archiwa Zagraniczne'), ('Other', 'Inne')], default='Other', help_text='Grupa źródeł', max_length=32),
        ),
    ]
