# Generated by Django 2.2.18 on 2021-12-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20210728_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_type', models.IntegerField(choices=[(0, 'Indexy'), (1, 'Skany')], default=0)),
                ('database_format', models.IntegerField(choices=[(0, 'Test'), (1, 'Wyszukiwarka PHP by MB'), (2, 'Geneteka'), (3, 'TGZC'), (4, 'SZwA'), (5, 'Lubgens'), (6, 'Poznan'), (7, 'Basia')])),
                ('url', models.URLField(blank=True)),
                ('check_date', models.DateTimeField(blank=True, null=True)),
                ('check_interval', models.IntegerField(default=1, help_text='Co ile dni sprawdzać zmiany')),
                ('raw_data', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parish',
            name='fs_catalog_id',
            field=models.CharField(blank=True, help_text='IDs w katalogu FamilySearch, rozdzielone spacjami', max_length=64),
        ),
        migrations.AlterField(
            model_name='parish',
            name='gen_id',
            field=models.IntegerField(blank=True, help_text='ID w genetece', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parish',
            name='szwa_id',
            field=models.CharField(blank=True, help_text='Zespół archiwalny xx/xxxx/x', max_length=64),
        ),
        migrations.CreateModel(
            name='RemoteSystemItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Nazwa obiektu, np. nazwa parafii', max_length=64)),
                ('raw_data', models.TextField(blank=True)),
                ('extra_url', models.URLField(blank=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.RemoteSystems')),
            ],
        ),
    ]
