# Generated by Django 2.2.18 on 2021-12-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211203_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesystems',
            name='active',
            field=models.BooleanField(default=False, help_text='Czy integracja ma być aktywna'),
        ),
    ]
