# Generated by Django 2.2.18 on 2021-12-05 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20211205_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesystems',
            name='name',
            field=models.TextField(default=django.utils.timezone.now, help_text='Nazwa bazy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remotesystems',
            name='database_format',
            field=models.IntegerField(choices=[(0, 'Test'), (1, 'Wyszukiwarka PHP by MB'), (2, 'Geneteka (@TODO)'), (3, 'TGZC'), (4, 'SZwA (@TODO)'), (5, 'Lubgens'), (6, 'Poznan (@TODO)'), (7, 'Basia (@TODO)')]),
        ),
    ]
