# Generated by Django 2.2.18 on 2021-12-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20211205_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishplace',
            name='note',
            field=models.TextField(blank=True, help_text='Notatka'),
        ),
        migrations.AddField(
            model_name='remotesystemitem',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Parish'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(blank=True, help_text='Diecezja', limit_choices_to=models.Q(country__historical_period=3), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Diocese'),
        ),
        migrations.AlterField(
            model_name='parish',
            name='province',
            field=models.ForeignKey(blank=True, help_text='Województwo (R3)', limit_choices_to=models.Q(country__historical_period=3), null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Province'),
        ),
        migrations.AlterField(
            model_name='parishplace',
            name='name',
            field=models.CharField(help_text='Nazwa', max_length=32),
        ),
        migrations.AlterField(
            model_name='parishplace',
            name='type',
            field=models.IntegerField(choices=[(0, 'Inny'), (1, 'Cmentarz'), (2, 'Miejscowość')], default=1),
        ),
        migrations.CreateModel(
            name='ParishNobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwisko', max_length=64)),
                ('nest', models.CharField(help_text='Gniazdo rodowe', max_length=64)),
                ('farmstead', models.CharField(help_text='PRZYSIÓŁEK', max_length=64)),
                ('arms', models.CharField(help_text='Herb', max_length=64)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lng', models.FloatField(blank=True, null=True)),
                ('parish', models.ForeignKey(help_text='Parafia', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Parish')),
            ],
        ),
    ]
