# Generated by Django 2.2.18 on 2021-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211205_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishplace',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parishplace',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remotesystems',
            name='database_type',
            field=models.IntegerField(choices=[(0, 'Indeksy'), (1, 'Skany')], default=0),
        ),
    ]
